services:
  postgres:
    image: postgres:18.1
    container_name: playground-pg
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ${VOLUME_PATH}/postgresql:/var/lib/postgresql
  redis:
    image: redis:8.4.0
    container_name: playground-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ${VOLUME_PATH}/redis:/data